### PR TITLE
SB-889 - sequelize adapter to postgres db

### PR DESCRIPTION
**Pull request by elkwood**
[SB-889](https://jira-issue-number.com)

@sprucelabsai/engineers

## Description 
This is should be tested in tandem with 
https://github.com/sprucelabsai/sprucebot-skills-kit/pull/61

## Type
- [x] Feature
- [ ] Bug
- [ ] Tech debt

## Steps to Test or Reproduce
Describe how to test the changes.

### CODE REVIEW

**Comment by lkkadiri** [comment]
@mcdermed How does one test this?

**Comment by elkwood** [comment]
@lkkadiri Is there something missing in the skills-kit PR? I'd like to to be usable for anyone using the README

**Comment by lkkadiri** [comment]
@mcdermed 
It says follow the Readme in that PR and when the link is clicked it points to a diff view to create a PR maybe the link in your how to test is busted?
```Follow the Readme dev...mcdermed:SB-889diff-04c6e90faac2675aa89e2176d2eec7d8R16```

**Comment by elkwood** [comment]
Link has been updated. https://github.com/sprucelabsai/sprucebot-skills-kit/pull/61/files#diff-04c6e90faac2675aa89e2176d2eec7d8R15

Hopefully the readme can get someone up and running

**Pull request merged**
